# Generated by Django 6.1 on 2026-09-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usua_id', models.BigAutoField(db_column='USUA_ID', primary_key=True, serialize=False)),
                ('usua_nomb', models.CharField(db_column='USUA_NOMB', max_length=100)),
                ('usua_tp_doc', models.CharField(db_column='USUA_TP_DOC', max_length=3, null=True)),
                ('usua_doc_id', models.CharField(db_column='USUA_DOC_ID', max_length=50, unique=True)),
                ('usua_tel', models.CharField(db_column='USUA_TEL', max_length=50, null=True)),
                ('usua_cor', models.CharField(db_column='USUA_COR', max_length=100, null=True)),
                ('password', models.CharField(db_column='USUA_PASS', max_length=255)),
            ],
            options={
                'db_table': 'USUARIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.BigAutoField(db_column='ROL_ID', primary_key=True, serialize=False)),
                ('rol_nomb', models.CharField(db_column='ROL_NOMB', max_length=50)),
                ('rol_desc', models.CharField(db_column='ROL_DESC', max_length=150)),
            ],
            options={
                'db_table': 'ROL',
                'managed': False,
            },
        ),
    ]
